#!/bin/bash

#Note must be executed from withing directory
#Args:
#1: path to simvascular binary
#2: path to run.tcl
#3: output directory
    #NOTE: output directory must contain images.txt, paths.txt, groups.txt edges.txt
    #as generated by make_svfile_lists.sh

echo "Input arguments: $1 $2 $3"
echo "Generating raw data using simvascular"
SV="/home/marsdenlab/projects/JSV/sv_build/mysim"
TCL="/home/marsdenlab/projects/tcl_code/tcl/run_models.tcl"
OUT="/home/marsdenlab/projects/tcl_code/python/output/9/vtk"
cd $3

cd $OUT
rm $OUT/*

for g in ../groups/*; do
  echo "$g"
  $SV $TCL $g &
  sleep 70
done

#
#$1 $2
